import profile from '../../../Images/Jpg/profile.jpg'
export const Data = [
    {
        username:'janvi_kannan',
        dpname:'Janvi',
        dp:profile,
        category:'follower'
    },
    {
        username:'___miniya___',
        dpname:'Alminaz',
        dp:profile,
        category:'following'
    },
    {
        username:'bishmajjr',
        dpname:'Bish',
        dp:profile,
        category:'follower'
    },
    {
        username:'janvi_kannan',
        dpname:'Janvi',
        dp:profile,
        category:'follower'
    },
    {
        username:'___miniya___',
        dpname:'Alminaz',
        dp:profile,
        category:'following'
    },
    {
        username:'bishmajjr',
        dpname:'Bish',
        dp:profile,
        category:'follower'
    },
    {
        username:'janvi_kannan',
        dpname:'Janvi',
        dp:profile,
        category:'follower'
    },
    {
        username:'___miniya___',
        dpname:'Alminaz',
        dp:profile,
        category:'following'
    },
    {
        username:'bishmajjr',
        dpname:'Bish',
        dp:profile,
        category:'follower'
    },
    {
        username:'janvi_kannan',
        dpname:'Janvi',
        dp:profile,
        category:'follower'
    },
    {
        username:'___miniya___',
        dpname:'Alminaz',
        dp:profile,
        category:'following'
    },
    {
        username:'bishmajjr',
        dpname:'Bish',
        dp:profile,
        category:'follower'
    },
]